### ISSUE TITLE
NCT6683

### ISSUE THREAD

**Issue by martin82private** [ich777/unraid-nct6687-driver#1]
Hi sorry if i m wrong here but after hours of googeling i give up :-)

I have a Thinkstation P700 and it seems to be it s using a NCT6683. Do you can add a NCT6683 driver?

> `Do you want to scan for Super I/O sensors? (YES/no): 
Probing for Super-I/O at 0x2e/0x2f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               Yes
**Found unknown chip with ID 0xb732**
Probing for Super-I/O at 0x4e/0x4f
Trying family `National Semiconductor/ITE'...               No
Trying family `SMSC'...                                     No
Trying family `VIA/Winbond/Nuvoton/Fintek'...               No
Trying family `ITE'...   `

thanks
Martin

**Comment by ich777** [comment]
@martin82private sorry for the late answer but I completely forgot about this.

Please keep in mind that this plugin is based on: https://github.com/Fred78290/nct6687d
AFAIK NCT6683 is a completely different sensor and won't work with this plugin.

**Comment by ich777** [comment]
Closing this issue due to no response, feel free to open the issue again or answer to the closed Issue if something else is needed.
